name: Andrew Valentine
bio: 'I fix computers. I also do other things on the internet.'
picture: 'assets/images/profile.jpg'

url: http://andrewvalentine.github.io
permalink: /:title/

markdown: kramdown
highlighter: rouge

analytics: 'UA-MYANALYTICS'
disqus: mydisqus
facebook: facebook.com/a.r.valentine
twitter: twitter.com/andrewvalentine
instagram: instagram.com/andrewvalentine
linkedin: https://uk.linkedin.com/in/andrewvalentine
spotify: https://open.spotify.com/user/igethitbyemokids
github: github.com/andrewvalentine
email: andrew@defaultswrite.co

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
#projects: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
